<?php

/**
 * Template du formulaire d'inscription.
 */

?>

<div class="connection-form">
    <form action="" method="post" class="foldedCorner">
        <h2>Inscription</h2>
        <div class="formGrid">
            <label for="nickname">Pseudonyme</label>
            <input type="text" name="nickname" id="nickname" value="<?= $this->clean($_POST['nickname'] ?? '', false) ?>" required>

            <label for="email">Email</label>
            <input type="email" name="email" id="email" value="<?= $this->clean($_POST['email'] ?? '', false) ?>" required>

            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password" required>

            <label for="confirm_password">Confirmez le mot de passe</label>
            <input type="password" name="confirm_password" id="confirm_password" required>
        </div>
        <hr>
        <span> J'ai lu et accepte les <a href="#">conditions d'utilisation</a></span>
        <button class="submit">S'inscrire</button>
    </form>
</div>