<?php

/**
 * Affichage de la partie admin : liste des articles sous forme de tableau avec un bouton "voir", "modifier" et "supprimer" pour chacun. 
 * Il est possible de trier les articles par titre, nombre de vues, nombre de commentaires ou date de sortie.
 * Et un lien vers le formulaire pour ajouter un article. 
 */

?>

<h2>Gestion des articles</h2>

<!-- Bouton Ajouter un article -->
<div class="admin-add-article">
    <a class="btn-add" href="<?= $this->url('/admin/addArticle') ?>">
        <i class="fa-solid fa-plus" style="font-size: 1em"></i> Ajouter un article <i class="fa-solid fa-plus" style="font-size: 1em"></i></a>
</div>
<table class="article-table">
    <thead class="hover-effect">
        <tr>
            <th><a class="hover-link" href="<?= $this->url('/admin', ['sort' => 'title', 'dir' => $this->toggleSort('title')]) ?>">Titre</a></th>
            <th><a class="hover-link" href="<?= $this->url('/admin', ['sort' => 'views', 'dir' => $this->toggleSort('views')]) ?>">Nombre de vues</a></th>
            <th><a class="hover-link" href="<?= $this->url('/admin', ['sort' => 'comments', 'dir' => $this->toggleSort('comments')]) ?>">Total de commentaires</a></th>
            <th><a class="hover-link" href="<?= $this->url('/admin', ['sort' => 'date_creation', 'dir' => $this->toggleSort('date_creation')]) ?>">Date de création</a></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($articles as $index => $article): ?>
            <!-- Si l'index est pair, on ajoute la classe "even", sinon on ajoute la classe "odd" -->
            <tr class="<?= $index % 2 === 0 ? 'even' : 'odd' ?>">
                <td><?= $this->clean($article['title']) ?></td>
                <td><?= $this->clean($article['views'], false) ?></td>
                <td><?= $this->clean($article['comments'], false) ?></td>
                <td><?= $this->formatDate($article['date_creation']) ?></td>
                <td>
                    <form class="form-actions" method="POST" action="<?= $this->url('/admin/delete/:id', ['id' => $article['id']]) ?>" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet article ?');">
                        <a class="btn-action btn-view tooltip" data-tooltip="Voir l'article" href="<?= $this->url('/articles/show/:id', ['id' => $article['id']]) ?>">
                            <i class="fa-regular fa-eye"></i>
                        </a>
                        <a class="btn-action btn-edit tooltip" data-tooltip="Modifier l'article" href="<?= $this->url('/admin/edit/:id', ['id' => $article['id']]) ?>">
                            <i class="fa-solid fa-pen-to-square"></i>
                        </a>
                        <button type="submit" class="btn-action btn-delete tooltip" data-tooltip="Supprimer l'article">
                            <i class="fa-solid fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>