<?php

/**
 * Template principal de l'application
 */

$this->initSession();

?>

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le Projet MVC OpenClassrooms">
    <title>Blog | <?= isset($title) ?  $this->clean($title, false) : 'Bienvenue' ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="<?= $this->url('../assets/CSS/style.css') ?>">
</head>

<body>
    <header>
        <nav class="hover-effect">
            <a class="hover-link" href="<?= $this->url('/articles') ?>">Articles</a>
            <a class="hover-link" href="<?= $this->url('/aPropos') ?>">À propos</a>
            <!-- Si on est admin, on affiche le bouton d'administration : -->
            <?php if ($this->isAdmin()): ?>
                <a class="hover-link" href="<?= $this->url('/admin') ?>">Administration</a>
            <?php endif ?>
            <!-- Si on est connecté, on affiche le bouton de déconnexion, sinon, on affiche le bouton de connexion : -->
            <?php if ($this->isAuthenticated()): ?>
                <a class="hover-link" href="<?= $this->url('/users/profile') ?>">Mon profil</a>
                <a class="hover-link" href="<?= $this->url('/auth/disconnect') ?>" onclick="return confirm('Etes-vous sur de vouloir vous déconnecter ?')">Déconnexion</a>
            <?php else: ?>
                <a class="hover-link" href="<?= $this->url('/auth/connection') ?>">Connexion</a>
                <a class="hover-link" href="<?= $this->url('/auth/registration') ?>">Inscription</a>
            <?php endif ?>
        </nav>
        <h1>Emilie Forteroche</h1>

    </header>
    <!-- Affichage des messages error, success et warning -->
    <?php $this->renderFlash(); ?>
    <main class="main-content">
        <?php include $template; ?>
    </main>

    <!-- Footer -->
    <footer class="footer hover-effect">
        <p>&copy; <?= date('Y') ?> Mon Super Site MVC. Tous droits réservés.</p>
    </footer>
    <script src="<?= $this->url('/JS/app.js') ?>" type="module"></script>

</body>

</html>