<?php

/**
 * Ce template affiche un article et ses commentaires.
 * Il affiche également un formulaire pour ajouter un commentaire. -->
 */
?>

<!-- boutons retour et gestion article -->
<div class="container-over-links">
    <?php if ($this->isAdmin()): ?>
        <a href="<?= $this->url('/admin') ?>" class="linkBack link-left">🔧 Gestion des articles 🔧</a>
    <?php else: ?>
        <a href="<?= $this->url('/articles') ?>" class="linkBack link-left"><span style="font-size: 2em;">&#9756;</span>
            Retour aux articles <span style="font-size: 2em;">&#9756;</span>
        </a>
    <?php endif; ?>
    <div class="link-group">
        <?php if ($this->isAdmin()): ?>
            <a href="<?= $this->url('/admin/edit/' . $article['id']) ?>" class="linkBack">&#9998; Éditer &#9998;</a>
            <form class="form-actions" method="POST" action="<?= $this->url('/admin/delete/:id', ['id' => $article['id']]) ?>" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet article ?');">
                <button type="submit" class="linkBack link-delete"><i class="fa-solid fa-trash"></i> Supprimer
                    <i class="fa-solid fa-trash"></i>
                </button>
            </form>
        <?php endif; ?>
    </div>
</div>
<!-- Détails de l'article -->
<article class="mainArticle">
    <h2> <?= $this->clean($title ?? 'Détails de l\'article') ?> </h2>
    <span class="quotation">«</span>
    <p><?= $this->clean($article['content']) ?></p>
    <!-- Bas de page de l'article -->
    <div class="footer">
        <span class="info"> Publié le <?= $this->formatDate($article['date_creation'], 'full') ?></span>
        <?php if ($article['date_update'] != null): ?>
            <span class="info"> Modifié le <?= $this->formatDate($article['date_update'], 'full') ?></span>
        <?php endif ?>
        <hr>
        <span class="info info-views"><i class="fa-regular fa-eye"></i>
            Nombre de vues <i class="fa-regular fa-eye"></i> :
            <?= $this->clean($article['views'], false) ?></span>
    </div>
</article>
<!-- Section des commentaires -->
<div class="comments">
    <h2 class="commentsTitle">Vos Commentaires</h2>
    <?php if (empty($comments)): ?>
        <p class="info">Aucun commentaire pour cet article.</p>
    <?php else: ?>
        <ul>
            <?php foreach ($comments as $comment): ?>
                <li id="comment-<?= $comment['id'] ?>" class="comment-item">
                    <div class="comment-content">
                        <div class="smiley">☻</div>
                        <div class="detailComment">
                            <h3 class="info">
                                Le <?= $this->formatDate($comment['date_creation'], 'long'); ?>,
                                <?= $this->clean($comment['pseudo'], false) ?> a écrit :
                            </h3>
                            <p class="content"><?= $this->clean($comment['content']) ?></p>
                        </div>
                    </div>
                    <!-- Bouton supprimer, visible uniquement si admin -->
                    <?php if ($this->isAdmin()): ?>
                        <form class="delete-form tooltip" data-tooltip="Supprimer ce commentaire" method="POST" action="<?= $this->url('/comment/delete/:id', ['id' => $comment['id']]) ?>" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce commentaire ?');">
                            <!-- <input type="hidden" name="id_article" value="<?= $article['id'] ?>"> -->
                            <button class="delete-comment" type="submit">x</button>
                        </form>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
    <!-- Formulaire d'ajout de commentaire -->
    <form action="<?= $this->url('/addComment') ?>" method="post" class="foldedCorner">
        <h2>Commenter</h2>
        <div class="formComment formGrid">
            <label for="pseudo">Pseudonyme</label>
            <input type="text" name="pseudo" id="pseudo" required>

            <label for="content">Commentaire</label>
            <textarea name="content" id="content" required></textarea>

            <input type="hidden" name="action" value="addComment">
            <input type="hidden" name="idArticle" value="<?= $article['id'] ?>">

            <button class="submit">Ajouter un commentaire</button>
        </div>
    </form>
</div>