# Rôle : Déclare toutes les routes disponibles dans l'application.
# Fonctionnement :
# Liste les chemins (URI) associés à des méthodes HTTP (GET, POST, etc.).
# Associe chaque route à une "action" dans un contrôleur (ex. : App\Controller\IndexAction).

routes:
  "/":
    method: GET
    callable: App\Controller\ArticleController::listAllArticles

  # Route Authentication
  # Inscription
  "/auth/registration":
    method:
      - POST
      - GET
    callable: App\Controller\AuthController::register
  # Connexion
  "/auth/connection":
    method:
      - POST
      - GET
    callable: App\Controller\AuthController::connect
  # Deconnexion
  "/auth/disconnect":
    method: GET
    callable: App\Controller\AuthController::disconnect

  # Route pour la gestion des utilisateurs
  # Espace utilisateur
  "/users/profile":
    method: GET
    callable: App\Controller\UserController::profile
  # Formulaire de modification de profil
  "/users/editProfile":
    method: GET
    callable: App\Controller\UserController::editProfile
  # Modification de profil
  "/users/updateProfile":
    method: POST
    callable: App\Controller\UserController::updateProfile
  # Suppression de compte
  "/users/deleteAccount":
    method: POST
    callable: App\Controller\UserController::deleteAccount

  # Routes Administration
  # Tableau de gestion des articles
  "/admin":
    method: GET
    callable: App\Controller\AdminController::showAdmin
  # Ajouter un article
  "/admin/addArticle":
    method:
      - POST
      - GET
    callable: App\Controller\AdminController::addArticle
  # Modifier un article
  "/admin/edit/:id":
    method:
      - POST
      - GET
    callable: App\Controller\AdminController::editArticle
  # Supprimer un article
  "/admin/delete/:id":
    method: POST
    callable: App\Controller\AdminController::deleteArticle

  # Route pour visualiser les articles
  # Tous
  "/articles":
    method: GET
    callable: App\Controller\ArticleController::listAllArticles
  # Un seul
  "/articles/show/:id":
    method: GET
    callable: App\Controller\ArticleController::showArticleDetails

  # A propos
  "/aPropos":
    method: GET
    callable: App\Controller\ArticleController::showApropos

  # Route pour la gestion des commentaires (admin)
  # Formulaire d'ajout de commentaire
  "/addComment":
    method: POST
    callable: App\Controller\CommentController::addComment
  # Suppression de commentaire
  "/comment/delete/:id":
    method: POST
    callable: App\Controller\CommentController::delete
