<?php

/**
 * Vue affichant le profil de l'utilisateur connecté.
 */

?>

<div class="profile-container">
    <h2>Mon profil</h2>

    <div class="profile-info">
        <p><strong>Nom d'utilisateur :</strong> <?= $this->clean($user['nickname'], false); ?></p>
        <p><strong>Email :</strong> <?= $this->clean($user['email'], false); ?></p>
    </div>

    <hr>

    <div class="profile-actions">
        <a href="<?= $this->url('/users/editProfile'); ?>" class="btn btn-edit"> <i class="fa-solid fa-pen-to-square"></i>
            Modifier mes informations</a>

        <form method="POST" class="form-actions" action="<?= $this->url('/users/deleteAccount'); ?>" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible.');">
            <button type="submit" class="btn btn-delete"> <i class="fa-solid fa-trash"></i>
                Supprimer mon compte</button>
        </form>
    </div>
</div>